/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pHjOelYtNZX
 */
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div className="bg-[#0d1117] text-white min-h-screen">
      <nav className="flex justify-between items-center py-4 px-8">
        <div className="flex space-x-4">
          <Avatar>
            <AvatarImage alt="Profile picture" src="/placeholder.svg?height=40&width=40" />
          </Avatar>
          <span
            className="bg-green-500 rounded-full px-3 py-1 text-xs font-semibold text-white">
            Disponible para trabajar
          </span>
        </div>
        <div className="flex space-x-6">
          <Link className="text-white hover:text-gray-300" href="#">
            Experiencia
          </Link>
          <Link className="text-white hover:text-gray-300" href="#">
            Proyectos
          </Link>
          <Link className="text-white hover:text-gray-300" href="#">
            Sobre mí
          </Link>
          <Link className="text-white hover:text-gray-300" href="#">
            Contacto
          </Link>
          <ShoppingCartIcon className="text-white" />
        </div>
      </nav>
      <header className="px-8 mt-12">
        <h1 className="text-4xl font-bold">Hey, soy John Doe</h1>
        <p className="mt-4 text-xl">
          +15 años de experiencia. Ingeniero de Software y Creador de Contenido Digital de Barcelona, España.
          Especializado en el desarrollo de aplicaciones web únicas.
        </p>
        <div className="mt-6">
          <Button className="mr-4" variant="outline">
            Contáctame
          </Button>
          <Button variant="ghost">LinkedIn</Button>
        </div>
      </header>
      <section className="px-8 mt-12">
        <h2 className="text-3xl font-bold">Experiencia laboral</h2>
        <div className="mt-6">
          <div className="flex items-start space-x-4">
            <BriefcaseIcon className="text-yellow-500" />
            <div>
              <h3 className="text-xl font-semibold">Creador de Contenido</h3>
              <p className="text-sm text-gray-400">Twitch</p>
              <p className="text-sm">Actualmente...</p>
              <p className="mt-2 text-sm">
                Divulgo sobre programación y desarrollo web en diferentes plataformas. Galardonado como mejor creador de
                contenido de habla no-inglesa en 2022 y mejor comunidad en 2023 por GitHub.
              </p>
              <Link className="text-blue-500 hover:underline mt-2 inline-block" href="#">
                Saber más
              </Link>
            </div>
          </div>
          <div className="flex items-start space-x-4 mt-8">
            <BriefcaseIcon className="text-yellow-500" />
            <div>
              <h3 className="text-xl font-semibold">Principal Frontend Engineer</h3>
              <p className="text-sm text-gray-400">Adevinta Spain</p>
              <p className="text-sm">
                Responsable de la plataforma, componentes y utilidades para la creación y desarrollo de aplicaciones
                web. Mejora de un 30% en la entrega de software. Implantación de medidas de...
              </p>
              <Link className="text-blue-500 hover:underline mt-2 inline-block" href="#">
                Saber más
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>)
  );
}


function ShoppingCartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path
        d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>)
  );
}


function BriefcaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>)
  );
}
