/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kSKDXuLE0rx
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function Component2() {
  return (
    (<div className="bg-white p-8">
      <h2 className="text-2xl font-bold mb-6">Proyectos</h2>
      <div className="grid grid-cols-2 gap-6">
        <Card className="w-full">
          <CardHeader>
            <CardTitle>mars.codes</CardTitle>
            <Badge variant="secondary">En desarrollo</Badge>
          </CardHeader>
          <CardContent>
            <p>Historia interactiva con retos de programación para viajar a Marte</p>
          </CardContent>
          <CardFooter className="flex justify-between">
            <Button variant="outline">Elige tu propia aventura</Button>
          </CardFooter>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>AdventJS</CardTitle>
            <Badge variant="secondary">Multimedia</Badge>
            <Badge variant="secondary">JavaScript & TypeScript</Badge>
          </CardHeader>
          <CardContent>
            <p>Retos de programación en JavaScript para cada día de diciembre hasta Navidad</p>
          </CardContent>
          <CardFooter className="flex justify-between">
            <p className="text-sm">+1 millón de visitas</p>
          </CardFooter>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>codi.link</CardTitle>
            <InfoIcon className="text-gray-400" />
          </CardHeader>
          <CardContent>
            <p>Playground de código HTML, CSS y JavaScript para compartir</p>
          </CardContent>
          <CardFooter className="flex justify-between">
            <p className="text-sm">100k visitas al mes</p>
            <Badge variant="secondary">Desarrollado por la comunidad</Badge>
          </CardFooter>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>Pruebas Técnicas</CardTitle>
            <InfoIcon className="text-gray-400" />
          </CardHeader>
          <CardContent>
            <p>Lista de pruebas técnicas de empresas para practicar programación</p>
          </CardContent>
          <CardFooter className="flex justify-between">
            <p className="text-sm">100% gratuito</p>
            <p className="text-sm">+500 soluciones de la comunidad</p>
          </CardFooter>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>Codember</CardTitle>
            <Badge variant="secondary">+2000 usuarios activos</Badge>
          </CardHeader>
          <CardContent>
            <p>Juego interactivo de programación con retos y secretos</p>
          </CardContent>
          <CardFooter className="flex justify-between">
            <p className="text-sm">Retos para cualquier lenguaje</p>
          </CardFooter>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>miduConf</CardTitle>
          </CardHeader>
          <CardContent>
            <p>Conferencia de programación en streaming para la comunidad hispanohablante con charlas top</p>
          </CardContent>
          <CardFooter className="flex justify-between">
            <p className="text-sm">+15k tickets repartidos</p>
            <p className="text-sm">+50k espectadores en directo</p>
          </CardFooter>
        </Card>
      </div>
      <div className="mt-12">
        <h3 className="text-xl font-semibold mb-4">Habilidades</h3>
        <div className="flex flex-wrap gap-2">
          <Badge>HTML</Badge>
          <Badge>CSS</Badge>
          <Badge>JavaScript</Badge>
          <Badge>Tailwind</Badge>
          <Badge>TypeScript</Badge>
          <Badge>Node</Badge>
          <Badge>MySQL</Badge>
          <Badge>Git</Badge>
          <Badge>GitHub</Badge>
          <Badge>Next.js</Badge>
          <Badge>React</Badge>
        </div>
      </div>
    </div>)
  );
}


function InfoIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>)
  );
}
