/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EfYqFdjyA8Q
 */
import Link from "next/link"
import { CardHeader, Card } from "@/components/ui/card"

export function Component() {
  return (
    (<section className="w-full py-12">
      <div className="container grid grid-cols-1 md:grid-cols-2 gap-12 px-4 md:px-6">
        <div className="flex flex-col justify-center space-y-4">
          <h2 className="text-3xl font-bold tracking-tight">Latest Projects</h2>
          <p className="text-gray-500 dark:text-gray-400">
            I'm a paragraph. Go to
            <Link className="underline" href="#">
              the next page
            </Link>
            to add your own text and edit me. I'm a great place for you to tell a story and let your users know a little
            more about you.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 md:gap-4">
          <Card>
            <CardHeader
              className="flex flex-col md:flex-row items-start md:items-center gap-2 p-4">
              <div className="text-center md:text-left">
                <h3 className="text-lg font-bold leading-none">Project Title</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Description of the project</p>
              </div>
              <div className="ml-auto flex gap-2 md:gap-4">
                <Link
                  className="inline-block rounded-lg border border-gray-200 dark:border-gray-800 p-2 text-sm font-semibold text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-850 hover:text-gray-900 dark:hover:text-gray-50 dark:border-gray-800"
                  href="#">
                  View Details
                </Link>
              </div>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader
              className="flex flex-col md:flex-row items-start md:items-center gap-2 p-4">
              <div className="text-center md:text-left">
                <h3 className="text-lg font-bold leading-none">Project Title</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Description of the project</p>
              </div>
              <div className="ml-auto flex gap-2 md:gap-4">
                <Link
                  className="inline-block rounded-lg border border-gray-200 dark:border-gray-800 p-2 text-sm font-semibold text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-850 hover:text-gray-900 dark:hover:text-gray-50 dark:border-gray-800"
                  href="#">
                  View Details
                </Link>
              </div>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader
              className="flex flex-col md:flex-row items-start md:items-center gap-2 p-4">
              <div className="text-center md:text-left">
                <h3 className="text-lg font-bold leading-none">Project Title</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Description of the project</p>
              </div>
              <div className="ml-auto flex gap-2 md:gap-4">
                <Link
                  className="inline-block rounded-lg border border-gray-200 dark:border-gray-800 p-2 text-sm font-semibold text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-850 hover:text-gray-900 dark:hover:text-gray-50 dark:border-gray-800"
                  href="#">
                  View Details
                </Link>
              </div>
            </CardHeader>
          </Card>
        </div>
      </div>
    </section>)
  );
}
